//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CookingCourseListData.java
//  @ Date : 2014-04-28
//  @ Author : ¾çÁø¿µ
//
//



import java.util.*;
public class CookingCourseListData {
	private Collection<CookingCourseList> cookingCourseListData;
	
	public CookingCourseListData() {
		this(new LinkedList<CookingCourseList>());
	}
	public CookingCourseListData(Collection<CookingCourseList> cookingCourseListData) {
		this.cookingCourseListData=cookingCourseListData;
	}
	
	public Collection<CookingCourseList> getCookingCourseListData() {
		return this.cookingCourseListData;
	}
	
	public void setCookingCoureListData(Collection<CookingCourseList> cookingCourseListData) {
		this.cookingCourseListData=cookingCourseListData;
	}
	
	public CookingCourseList addCookingCourseList(CookingCourseList cookingCourseList) {
		if(cookingCourseListData.add(cookingCourseList))
		{
			return cookingCourseList;
		}
		else
		{
			return null;
		}
	}
	public CookingCourseList reviseCookingCourseList(CookingCourseList searchData,CookingCourseList reviseData) {
		int i=0;
		for(CookingCourseList tmp:cookingCourseListData)
		{
			if(tmp.getFoodCode().equals(searchData.getFoodCode()))
			{
				((LinkedList<CookingCourseList>)cookingCourseListData).set(i,reviseData);
				return reviseData;
			}
			i++;
		}
		return null;
	}
	
	public CookingCourseList removeCookingCourseList(CookingCourseList cookingCourseList) {
		if(cookingCourseListData.remove(searchCookingCourseList(cookingCourseList)))
		{
			return cookingCourseList;
		}
		else
		{
			return null;
		}
	}
	
	public CookingCourseList searchCookingCourseList(CookingCourseList cookingCourseList) {
		for(CookingCourseList tmp:cookingCourseListData)
		{
			if(tmp.getFoodCode().equals(cookingCourseList.getFoodCode()))
			{
				return tmp;
			}
		}
		return null;
	}
}
