//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CookingCourseRegistController.java
//  @ Date : 2014-04-29
//  @ Author : 
//
//


import javax.swing.*;
import java.awt.*;

public class CookingCourseRegistController {
	public String photoPath;
	public int time;
	public String description;
	public CookingCourseRegistController() 
	{
		this(new JTextField(),new JTextField(),new JTextArea());
	}
	
	public CookingCourseRegistController(JTextField photoPath, JTextField time, JTextArea description) 
	{
		this.photoPath = photoPath.getText();
		this.time = Integer.parseInt(time.getText());
		this.description = description.getText();
	}
	public void tempRegister()
	{
		CookingCourse obj = new CookingCourse(photoPath,time,description);
		TempCookingCourseList.addCookingCourse(obj);
		
		//getFoodRecipeInfoList
		/*Å×½ºÆ® 
		for(CookingCourse temp : TempCookingCourseList.getCookingCourseList())
		{
			System.out.println(temp.getCookingPhoto());
			System.out.println(temp.getCookingTime());
			System.out.println(temp.getCookingInst());
		}*/
	}
	public String getPhotoPath() 
	{
		return this.photoPath;
	}
	
	public int getTime()
	{
		return this.time;
	}
	
	public String getDescription() 
	{
		return this.description;
	}
	
	public void setPhotoPath(String photoPath) 
	{
		this.photoPath= photoPath;
	}
	
	public void setTime(int time) 
	{
		this.time =time;
	}
	
	public void setDescription(String description) 
	{
		this.description =description;
	}
}
