//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FoodCategoryList.java
//  @ Date : 2014-05-13
//  @ Author : ¾çÁø¿µ
//
//



import java.util.*;
public class FoodCategoryList {
	private Collection<FoodCategoryDTO> foodCategoryList;
	public FoodCategoryList() {
		this(new LinkedList<FoodCategoryDTO>());
	}
	
	public FoodCategoryList(Collection<FoodCategoryDTO> foodCategoryList) {
		this.foodCategoryList=foodCategoryList;
	}
	
	public FoodCategoryDTO addFoodCategoryList(FoodCategoryDTO foodCategoryDTO) {
		if (foodCategoryList.add(foodCategoryDTO))
			return foodCategoryDTO;
		else
			return null;
	}
	
	public FoodCategoryDTO removeFoodCategoryList(FoodCategoryDTO foodCategoryDTO) {
		if(foodCategoryList.remove(foodCategoryDTO))
			return foodCategoryDTO;
		else
			return null;
	}
	
	public FoodCategoryDTO reviseFoodCategoryList(FoodCategoryDTO exFoodCategoryDTO, FoodCategoryDTO newFoodCategoryDTO) {
		int i=0;
		for(FoodCategoryDTO tmp:foodCategoryList)
		{
			if(tmp.getFoodCategoryCode()==exFoodCategoryDTO.getFoodCategoryCode())
			{
				((LinkedList<FoodCategoryDTO>)foodCategoryList).set(i,newFoodCategoryDTO);
				return tmp;
			}
			i++;
		}
		return null;
	}
	
	public FoodCategoryDTO searchFoodCategoryList(FoodCategoryDTO foodCategoryDTO) {
		for(FoodCategoryDTO tmp:foodCategoryList)
		{
			if(tmp.getFoodCategoryCode()==foodCategoryDTO.getFoodCategoryCode())
			{
				return tmp;
			}
		}
		return null;
	}
	public Collection<FoodCategoryDTO> getFoodCategoryList()
	{
		return foodCategoryList;
	}
	public void setFoodCategoryList(Collection<FoodCategoryDTO> foodCategoryList)
	{
		this.foodCategoryList=foodCategoryList;
	}
}
