//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FoodInfoList.java
//  @ Date : 2014-04-28
//  @ Author : ¾çÁø¿µ
//
//



import java.util.*;
public class FoodInfoList {
	private Collection<FoodInfo> foodInfoList;
	public FoodInfoList() {
		this(new LinkedList<FoodInfo>());
	}
	
	public FoodInfoList(Collection<FoodInfo> list) {
		this.foodInfoList=list;
	}
	
	public Collection<FoodInfo> getFoodInfoList() {
		return this.foodInfoList;
	}
	
	public void setFoodInfoList(Collection<FoodInfo> list) {
		this.foodInfoList=list;
	}
	
	public FoodInfo addFoodInfoList(FoodInfo foodInfo) {
		if(foodInfoList.add(foodInfo))
		{
			return foodInfo;
		}
		else
		{
			return null;
		}
	}
	public FoodInfo reviseFoodInfoList(String foodCode,FoodInfo foodInfo) {
		int i=0;
		for(FoodInfo tmp:foodInfoList)
		{
			if(tmp.getFoodCode().equals(foodCode))
			{
				((LinkedList<FoodInfo>)foodInfoList).set(i,foodInfo);
				return foodInfo;
			}
			i++;
		}
		return null;
	}
	
	public FoodInfo removeFoodInfoList(String foodCode) {
		for(FoodInfo tmp:foodInfoList)
		{
			if(tmp.getFoodCode().equals(foodCode))
			{
				foodInfoList.remove(tmp);
				return tmp;
			}
		}
		return null;
	}
	public FoodInfo searchFoodInfo(String foodCode) {
		for(FoodInfo temp:foodInfoList)
		{
			if(temp.getFoodCode().equals(foodCode))
				return temp;
		}
		return null;
	}
	public Collection<FoodInfo> searchFoodInfoList(String foodName) {
		
		LinkedList<FoodInfo> tmp=new LinkedList<FoodInfo>();
		for(FoodInfo temp:foodInfoList)
		{
			if(temp.getFoodName().equals(foodName))
				tmp.add(temp);
		}
		return tmp;
	}
}
