//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IngredientRegisterController.java
//  @ Date : 2014-04-29
//  @ Author : 장성봉
//  재료를 선택한 후 등록 버튼을 누를 경우의 리스너
//


import javax.swing.*;
import java.awt.event.*;
import java.util.*;
public class IngredientRegisterController {
	public RecipeIngreInfoList recipeIngreInfoList;
	public  IngredientRegisterController() 
	{
		this(new JLabel(),new JTextField(),new JTextField[]{new JTextField()},new JTextField[]{new JTextField()});
	}
	
	public IngredientRegisterController(JLabel recipeName, JTextField ingredientTotalNum, JTextField[] ingredientName, JTextField[] ingredientNum) 
	{
		LinkedList<RecipeIngreInfo> list = new LinkedList<RecipeIngreInfo>();
		RecipeIngreInfo obj1 = new RecipeIngreInfo();

		for(int cnt = 0; cnt < ingredientName.length; cnt++)
		{
			list.add(new RecipeIngreInfo(ingredientName[cnt].getText(),Integer.toString(FoodRecipeInfoList.getFoodRecipeInfoList().size()+1),Integer.parseInt(ingredientNum[cnt].getText())));
		}
		this.recipeIngreInfoList = new RecipeIngreInfoList(recipeName.getText(),"",list);	
	}
	
	public void register()
	{
		
		for(RecipeIngreInfo obj : recipeIngreInfoList.getRecipeIngreInfoList())
		{
			TempRecipeIngreInfoList.setFoodName(obj.getIngredientName());
			TempRecipeIngreInfoList.setFoodCode(Integer.toString(FoodRecipeInfoList.getFoodRecipeInfoList().size()+1)); 
			TempRecipeIngreInfoList.setRecipeInfoList(recipeIngreInfoList.getRecipeIngreInfoList());
		}
	}
	
	public RecipeIngreInfoList getRecipeIngreInfoList() 
	{
		return this.recipeIngreInfoList;
	}
	
	public void setRecipeIngreInfoList(RecipeIngreInfoList recipeIngreInfoList) 
	{
		this.recipeIngreInfoList = recipeIngreInfoList;
	}
}
