//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ManagerInfo.java
//  @ Date : 2014-04-28
//  @ Author : 
//
//




public class ManagerInfo {
	private String managerName;		//관리자 이름
	private String managerId;		//관리자 아이디
	private String managerPassword;	//관리자 비밀번호
	
	public ManagerInfo() {
		this("","","");
	}
	
	public ManagerInfo(String managerName, String managerId,String managerPassword) {
		this.managerName = managerName;
		this.managerId = managerId;
		this.managerPassword = managerPassword;
	}
	
	public String getManagerName() {
		return this.managerName;
	}
	
	public String getManagerId() {
		return this.managerId;
	}
	public String getManagerPassword()
	{
		return this.managerPassword;
	}
	public void setManagerName(String managerName) {
		this.managerName = managerName;
	}
	
	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}
	public void setManagerPassword(String managerPassword)
	{
		this.managerPassword = managerPassword;
	}
}

