//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OrderDetailDTO.java
//  @ Date : 2014-05-13
//  @ Author : 

public class OrderDetailDTO 
{
	private int orderInfoCode;
	private int num;
	private int goodsCode;

	public OrderDetailDTO() 
	{
		this(0,0,0);
	}
	public OrderDetailDTO(int orderInfoCode, int num, int goodsCode) 
	{
		this.orderInfoCode = orderInfoCode;
		this.num = num;
		this.goodsCode = goodsCode;
	}
	public int getOrderInfoCode() 
	{
		return orderInfoCode;
	}
	public int getNum() 
	{
		return num;
	}
	
	public int getGoodsCode() 
	{
		return goodsCode;
	}
	public void setOrderInfoCode(int orderInfoCode) 
	{
		this.orderInfoCode = orderInfoCode;
	}
	public void setNum(int num) 
	{
		this.num = num;
	}
	public void setGoodsCode(int goodsCode) 
	{
		this.goodsCode = goodsCode;
	}
	public String toString() 
	{
		return ""+orderInfoCode + num + goodsCode;
	}
}
