//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OrdererInfo.java
//  @ Date : 2014-04-28
//  @ Author : 장성봉
//
//




public class OrdererInfo {
	private String ordererName;		//주문자 이름
	private String ordererPhone;	//주문자 연락처
	public OrdererInfo() 
	{
		this("","");	
	}
	
	public OrdererInfo(String ordererName, String ordererPhone) 
	{
		this.ordererName = ordererName;
		this.ordererPhone= ordererPhone;
	}
	
	public String getOrdererName() {
		return this.ordererName;
	}
	
	public String getOrdererPhone() {
		return this.ordererPhone;
	}
	
	public void setOrdererName(String ordererName) {
		this.ordererName = ordererName;
	}
	
	public void setOrdererPhone(String ordererPhone) {
		this.ordererPhone= ordererPhone;
	}
}
