//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OrderDetailList.java
//  @ Date : 2014-05-13
//  @ Author : 
//
//

import java.util.*;

public class OrderDetailList 
{
	private Collection<OrderDetailDTO> orderDetailList;
	public OrderDetailList()
	{
		this(new LinkedList<OrderDetailDTO>());
	}
	public OrderDetailList(Collection<OrderDetailDTO> orderDetailList) 
	{
		this.orderDetailList = orderDetailList;
	}
	public OrderDetailDTO addOrderDetailList(OrderDetailDTO orderDetailDTO) 
	{
		if(orderDetailDTO != null)
		{
			orderDetailList.add(orderDetailDTO);
			return orderDetailDTO;
		}
		return null;
	}
	public OrderDetailDTO removeOrderDetailList(OrderDetailDTO orderDetailDTO) 
	{
		OrderDetailDTO temp = searchOrderDetailList(orderDetailDTO);
		if(temp != null)
		{
			orderDetailList.remove(temp);
			return temp;
		}
		return null;
	
	}
	public OrderDetailDTO reviseOrderIDetailList(OrderDetailDTO exOrderDetailDTO, OrderDetailDTO newOrderDetailDTO) 
	{
		int i = 0;
		for(OrderDetailDTO temp : orderDetailList)
		{
			if(temp.getOrderInfoCode() == exOrderDetailDTO.getOrderInfoCode())
			{
				((LinkedList<OrderDetailDTO>) orderDetailList).set(i,newOrderDetailDTO);
			}
			i++;
		}
		return newOrderDetailDTO;
	}
	public OrderDetailDTO searchOrderDetailList(OrderDetailDTO orderDetailDTO) 
	{
		for(OrderDetailDTO temp : orderDetailList)
		{
			if(temp.getOrderInfoCode() == orderDetailDTO.getOrderInfoCode())
				return temp;
		}
		return null;
	}
	public Collection<OrderDetailDTO> getOrderDetailList()
	{
		return orderDetailList;
	}
	public void setOrderDetailList(Collection<OrderDetailDTO> orderDetailList)
	{
		this.orderDetailList=orderDetailList;
	}
}
