//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OrderedItemInfo.java
//  @ Date : 2014-04-28
//  @ Author : 장성봉
//
//




public class OrderedItemInfo {
	private String itemName;			//1개의 주문문물품명
	private String itemCode;			//1개의 주문물품코드
	private int itemNum;				//1개의 주문물품개수
	private double price;				//1개의 주문물품가격
	public OrderedItemInfo() 
	{
		this("","",0,0.0);
	}
	
	public OrderedItemInfo(String itemName,int itemNum, double price) 
	{
		this(itemName,"",itemNum,price);
	}
	
	public OrderedItemInfo(String itemName, String itemCode, int itemNum, double price) 
	{
		this.itemName = itemName;
		this.itemCode= itemCode;
		this.itemNum =itemNum;
		this.price =price;
	}
	
	public String getItemName() {
		return this.itemName;
	}
	
	public int getItemNum() {
		return this.itemNum;
	}
	
	public String getItemCode() {
		return this.itemCode;
	}
	
	public double getPrice() {
		return this.price;
	}
	
	public void setItemName(String itemName) {
		this.itemName = itemName;
	}
	public void setItemCode(String itemCode) {
		this.itemCode =itemCode;
	}
	public void setItemNum(int itemNum) {
		this.itemNum = itemNum;
	}
	
	public void setPrice(double price) {
		this.price = price;
	}
	
	
}
