//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OrderDetailDAO.java
//  @ Date : 2014-05-13
//  @ Author : 
//
//

import java.sql.*;


public class OrderDetailDAO 
{
	private Connection conn;

	public OrderDetailDAO() 
	{
		connect();
	}	
	private void connect() 
	{
		DBConnectionPool instance = DBConnectionPool.getInstance();
		try
		{
			conn=instance.getConnection();	
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
	}
	public void disconnect() 
	{
		try
		{
			if(conn != null)
			{
				conn.close();
				System.out.println("DB와의 접속을 끊었습니다.");
			}
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
	
	}
	public int insert(int orderInfoCode, int num, int goodsCode) 
	{
		int rowNum = 0;
		Statement stmt = null;
		try
		{
			stmt = conn.createStatement();
			rowNum = stmt.executeUpdate("insert into orderdetail_tb values("+orderInfoCode+","+num+","+goodsCode+")");
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch(Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return rowNum;
	}
	public OrderDetailList selectAll() 
	{
		OrderDetailDTO info = null;
		Statement stmt = null;
		OrderDetailList list = new OrderDetailList();

		try
		{
			stmt = conn.createStatement();
			ResultSet rs = stmt.executeQuery("select * from orderDetail_tb");
			while(rs.next())
			{
				int orderInfoCode = rs.getInt("orderInfoCode");
				int num = rs.getInt("num");
				int goodsCode = rs.getInt("goodsCode");
				
				info = new OrderDetailDTO(orderInfoCode,num,goodsCode);
				list.addOrderDetailList(info);
			}
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return list;
		
	
	}
	
	public OrderDetailDTO selecteOrderInfoCode(int orderInfoCode) 
	{
		OrderDetailDTO info = null;
		Statement stmt = null;
		

		try
		{
			stmt = conn.createStatement();
			ResultSet rs = stmt.executeQuery("select * from orderDetail_tb where orderInfoCode = "+orderInfoCode+"");
			while(rs.next())
			{
				int orderInfoCode1 = rs.getInt("orderInfoCode");
				int num = rs.getInt("num");
				int goodsCode = rs.getInt("goodsCode");
				
				info = new OrderDetailDTO(orderInfoCode1,num,goodsCode);
				
			}
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return info;
	}
	
	public OrderDetailList selecteNum(int num) 
	{	
		OrderDetailDTO info = null;
		Statement stmt = null;
		OrderDetailList list = new OrderDetailList();

		try
		{
			stmt = conn.createStatement();
			ResultSet rs = stmt.executeQuery("select * from orderDetail_tb where numum = "+num+"");
			while(rs.next())
			{
				int orderInfoCode = rs.getInt("orderInfoCode");
				int num1 = rs.getInt("num");
				int goodsCode = rs.getInt("goodsCode");
				
				info = new OrderDetailDTO(orderInfoCode,num1,goodsCode);
				list.addOrderDetailList(info);
			}
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return list;
	
	}
	
	public OrderDetailList selecteGoodsCode(int goodsCode) 
	{
		OrderDetailDTO info = null;
		Statement stmt = null;
		OrderDetailList list = new OrderDetailList();

		try
		{
			stmt = conn.createStatement();
			ResultSet rs = stmt.executeQuery("select * from orderDetail_tb where goodsCode = "+goodsCode+"");
			while(rs.next())
			{
				int orderInfoCode = rs.getInt("orderInfoCode");
				int num = rs.getInt("num");
				int goodsCode1 = rs.getInt("goodsCode");
				
				info = new OrderDetailDTO(orderInfoCode,num,goodsCode1);
				list.addOrderDetailList(info);
			}
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return list;
	}
	
	public int updateAll(int orderInfoCode, int num, int goodsCode) 
	{
		int res = 0;
		Statement stmt = null;
		try
		{
			stmt = conn.createStatement();
			res = stmt.executeUpdate("update orderDetail_tb set num = "+num+",goodsCode = "+goodsCode+" where orderInfoCode = "+orderInfoCode+"");
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return res;
	
	}
	
	public int updateNum(int orderInfoCode, int num) 
	{
		int res = 0;
		Statement stmt = null;
		try
		{
			stmt = conn.createStatement();
			res = stmt.executeUpdate("update orderDetail_tb set num = "+num+" where orderInfoCode = "+orderInfoCode+"");
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return res;
	}
	
	public int updateGoodsCode(int orderInfoCode, int goodsCode) 
	{
		int res = 0;
		Statement stmt = null;
		try
		{
			stmt = conn.createStatement();
			res = stmt.executeUpdate("update orderDetail_tb set goodsCode = "+goodsCode+" where orderInfoCode = "+orderInfoCode+"");
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return res;
	}
	
	public int deleteAll() 
	{
		int res = 0;
		Statement stmt = null;
		try
		{
			stmt = conn.createStatement();
			res = stmt.executeUpdate("delete from orderDetail_tb ");
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return res;
	}
	
	public int deleteOrderInfoCode(int orderInfoCode) 
	{
		int res = 0;
		Statement stmt = null;
		try
		{
			stmt = conn.createStatement();
			res = stmt.executeUpdate("delete from orderDetail_tb where orderInfoCode = "+orderInfoCode+" ");
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return res;
	}
	
	public int deleteNum(int num) 
	{
		int res = 0;
		Statement stmt = null;
		try
		{
			stmt = conn.createStatement();
			res = stmt.executeUpdate("delete from orderDetail_tb where num = "+num+"");
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return res;
	}
	
	public int deleteGoodsCode(int goodsCode) 
	{
		int res = 0;
		Statement stmt = null;
		try
		{
			stmt = conn.createStatement();
			res = stmt.executeUpdate("delete from orderDetail_tb where goodsCode  = "+goodsCode+" ");
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return res;
	}
	
	//------------------------ get/set --------------------
	public Connection getConn() 
	{
		return conn;
	}
	
	public void setConn(Connection conn) 
	{
		this.conn = conn;
	}
	
}
