//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OrderController.java
//  @ Date : 2014-04-29
//  @ Author : 
//
//
import javax.swing.*;
public class OrderController {
	private RecipeIngreInfoList recipeIngreInfoList;
	public void OrderController() {
	
	}
	
	public void OrderController(JFrame frame, JLabel recipeName, JCheckBox[] checkBox, JSpinner[] spinner) {
	
	}
	
	public void saveOrder() {
	
	}
	
	public RecipeIngreInfoList getRecipeIngreInfoList() {
		return null;
	
	}
	
	public void setRecipeIngreInfoList(RecipeIngreInfoList recipeIngreInfoList) {
	
	}
}
