//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OriginDAO.java
//  @ Date : 2014-05-13
//  @ Author : 양진영
//
//

import java.sql.*;
import java.util.*;

public class OriginDAO {
	private Connection conn;
	public OriginDAO() {
		connect();
	}
	
	private void connect() {
		try
		{
			conn=DBConnectionPool.getInstance().getConnection();
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
	}
	
	public void disconnect() {
		try
		{
			if(conn!=null)
			{
				conn.close();
				System.out.println("DB와의 접속을 끊었습니다.");
			}
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
	
	}
	
	public int insert(int originCode, String originName) {
		int rowNum=0;
		PreparedStatement pstmt=null;
		try
		{
			String sql="INSERT INTO origin_tb VALUES(?,?)";
			pstmt=conn.prepareStatement(sql);
			pstmt.setInt(1,originCode);
			pstmt.setString(2,originName);
			rowNum=pstmt.executeUpdate();
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch(Exception ex)
		{
			System.out.println(ex.getMessage());
		}
		finally
		{
			try
			{
				if(pstmt!=null)
					pstmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return rowNum;
	}
	
	public OriginList selectAll() {
		OriginList tmp=new OriginList();
		OriginDTO dto=null;
		PreparedStatement pstmt=null;
		try
		{
			String sql="SELECT * FROM Origin_tb";
			pstmt=conn.prepareStatement(sql);
			ResultSet rs=pstmt.executeQuery();
			while(rs.next())
			{
				dto=new OriginDTO(rs.getInt("originCode"),rs.getString("originName"));
				tmp.addOriginList(dto);
			}
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch(Exception ex)
		{
			System.out.println(ex.getMessage());
		}
		finally
		{
			try
			{
				if(pstmt!=null)
					pstmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return tmp;
	}
	
	public OriginDTO selectOriginCode(int originCode) {
		OriginDTO dto=null;
		PreparedStatement pstmt=null;
		try
		{
			String sql="SELECT * FROM Origin_tb WHERE originCode=?";
			pstmt=conn.prepareStatement(sql);
			pstmt.setInt(1,originCode);
			ResultSet rs=pstmt.executeQuery();
			while(rs.next())
			{
				dto=new OriginDTO(rs.getInt("originCode"),rs.getString("originName"));
			}
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch(Exception ex)
		{
			System.out.println(ex.getMessage());
		}
		finally
		{
			try
			{
				if(pstmt!=null)
					pstmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return dto;
	}
	
	public OriginList selectOriginName(String originName) {
		OriginList tmp=new OriginList();
		OriginDTO dto=null;
		PreparedStatement pstmt=null;
		try
		{
			String sql="SELECT * FROM Origin_tb WHERE originName LIKE'%?%'";
			pstmt=conn.prepareStatement(sql);
			pstmt.setString(1,originName);
			ResultSet rs=pstmt.executeQuery();
			while(rs.next())
			{
				dto=new OriginDTO(rs.getInt("originCode"),rs.getString("originName"));
				tmp.addOriginList(dto);
			}
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch(Exception ex)
		{
			System.out.println(ex.getMessage());
		}
		finally
		{
			try
			{
				if(pstmt!=null)
					pstmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return tmp;
	}
	
	public int updateName(int originCode, String originName) {
		int rowNum=0;
		PreparedStatement pstmt=null;
		try
		{
			String sql="UPDATE Origin_tb SET originName=? WHERE originCode=?";
			pstmt=conn.prepareStatement(sql);
			pstmt.setString(1,originName);
			pstmt.setInt(2,originCode);
			rowNum=pstmt.executeUpdate();
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch(Exception ex)
		{
			System.out.println(ex.getMessage());
		}
		finally
		{
			try
			{
				if(pstmt!=null)
					pstmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return rowNum;
	}
	
	public int deleteAll() {
		int rowNum=0;
		PreparedStatement pstmt=null;
		try
		{
			String sql="DELETE FROM Origin_tb";
			pstmt=conn.prepareStatement(sql);
			rowNum=pstmt.executeUpdate();
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch(Exception ex)
		{
			System.out.println(ex.getMessage());
		}
		finally
		{
			try
			{
				if(pstmt!=null)
					pstmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return rowNum;
	}
	
	public int deleteOriginCode(int originCode) {
		int rowNum=0;
		PreparedStatement pstmt=null;
		try
		{
			String sql="DELETE FROM origin_tb WHERE originCode=?";
			pstmt=conn.prepareStatement(sql);
			pstmt.setInt(1,originCode);
			rowNum=pstmt.executeUpdate();
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch(Exception ex)
		{
			System.out.println(ex.getMessage());
		}
		finally
		{
			try
			{
				if(pstmt!=null)
					pstmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return rowNum;
	}
	
	public int deleteOriginName(String originName) {
		int rowNum=0;
		PreparedStatement pstmt=null;
		try
		{
			String sql="DELETE FROM origin_tb WHERE originName LIKE '%?%'";
			pstmt=conn.prepareStatement(sql);
			pstmt.setString(1,originName);
			rowNum=pstmt.executeUpdate();
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch(Exception ex)
		{
			System.out.println(ex.getMessage());
		}
		finally
		{
			try
			{
				if(pstmt!=null)
					pstmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return rowNum;
	}
	
	public Connection getConn() {
		return conn;
	}
	public void setConn(Connection conn) {
		this.conn=conn;
	}
}
