//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : OriginList.java
//  @ Date : 2014-05-13
//  @ Author : 
//
//



import java.util.*;
public class OriginList {
	private Collection<OriginDTO> originList;
	public OriginList() {
		this(new LinkedList<OriginDTO>());
	}
	
	public OriginList(Collection<OriginDTO> originList) {
		this.originList=originList;
	}
	
	public OriginDTO addOriginList(OriginDTO originDTO) {
		
		if(originList.add(originDTO))
			return originDTO;
		else
			return null;
	}
	
	public OriginDTO removeOriginList(OriginDTO originDTO) {
		if(originList.remove(originDTO))
			return originDTO;
		else
			return null;
	}
	
	public OriginDTO reviseOriginList(OriginDTO exOriginDTO,OriginDTO newOriginDTO) {
		int i=0;
		for(OriginDTO tmp:originList)
		{
			if(tmp.getOriginCode()==newOriginDTO.getOriginCode())
			{
				((LinkedList<OriginDTO>)originList).set(i,newOriginDTO);
				return tmp;
			}
			i++;
		}
		return null;
	}
	
	public OriginDTO searchOriginList(OriginDTO originDTO) {
		for(OriginDTO tmp:originList)
		{
			if(tmp.getOriginCode()==originDTO.getOriginCode())
				return tmp;
		}
		return null;
	}
	public Collection<OriginDTO> getOriginList()
	{
		return originList;
	}
	public void setOriginList(Collection<OriginDTO> originList)
	{
		this.originList=originList;
	}
}
