//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RecipeIngredientList.java
//  @ Date : 2014-05-13
//  @ Author : 
//
//
import java.util.*;

public class RecipeIngredientList 
{
	private Collection<RecipeIngredientDTO> recipeIngredientList;
	public RecipeIngredientList() 
	{
		this(new LinkedList<RecipeIngredientDTO>());
	}	
	public RecipeIngredientList(Collection<RecipeIngredientDTO> recipeIngredientList) 
	{
		this.recipeIngredientList = recipeIngredientList;
	}
	public RecipeIngredientDTO addRecipeIngredientList(RecipeIngredientDTO recipeIngredientDTO) 
	{
		recipeIngredientList.add(recipeIngredientDTO);
		return recipeIngredientDTO;
	}
	public RecipeIngredientDTO removeRecipeIngredientList(RecipeIngredientDTO recipeIngredientDTO) 
	{
		RecipeIngredientDTO temp = searchRecipeIngredientList(recipeIngredientDTO);
		if(temp != null)
		{
			recipeIngredientList.remove(temp);
			return temp;
		}
		return null;
	}
	public RecipeIngredientDTO reviseRecipeIngredientList(RecipeIngredientDTO exRecipeIngredientDTO, RecipeIngredientDTO newRecipeIngredientDTO) 
	{
		int i = 0;
		for(RecipeIngredientDTO temp : recipeIngredientList)
		{
			if(temp.getRecipeIngredientCode() == exRecipeIngredientDTO.getRecipeIngredientCode())
			{
				((LinkedList<RecipeIngredientDTO>) recipeIngredientList).set(i,newRecipeIngredientDTO);
			}
			i++;
		}
		return newRecipeIngredientDTO;
	}
	public RecipeIngredientDTO searchRecipeIngredientList(RecipeIngredientDTO recipeIngredientDTO) 
	{
		for(RecipeIngredientDTO temp : recipeIngredientList)
		{
			if(temp.getRecipeIngredientCode()==recipeIngredientDTO.getIngredientCode())
			{
				return temp;
			}
		}
		return null;
	}
	public Collection<RecipeIngredientDTO> getRecipeIngredientList()
	{
		return recipeIngredientList;
	}
	public void setRecipeIngredientList(Collection<RecipeIngredientDTO> recipeIngredientList)
	{
		this.recipeIngredientList=recipeIngredientList;
	}
}
