//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RecipeCourseDTO.java
//  @ Date : 2014-05-13
//  @ Author : 장성봉
//
//




public class RecipeCourseDTO {
	private int courseLevel;
	private int recipeCode;
	private String recipeCoursePhoto;
	private int recipeCourseTime;
	private String recipeCourseIntro;
	public RecipeCourseDTO() 
	{
		this(0,0,"",0,"");
	}
	
	public RecipeCourseDTO(int courseLevel, int recipeCode, String recipeCoursePhoto, int recipeCourseTime, String recipeCourseIntro) 
	{
		this.courseLevel = courseLevel;
		this.recipeCode = recipeCode;
		this.recipeCoursePhoto = recipeCoursePhoto;
		this.recipeCourseTime = recipeCourseTime;
		this.recipeCourseIntro =recipeCourseIntro;
	}
	
	public int getCourseLevel() 
	{
		return this.courseLevel;
	}
	
	public int getRecipeCode() {
		return this.recipeCode;
	}
	
	public String getRecipeCoursePhoto() {
		return this.recipeCoursePhoto;
	}
	
	public int getRecipeCourseTime() {
		return this.recipeCourseTime;
	}
	
	public String getRecipeCourseIntro() {
		return this.recipeCourseIntro;
	}
	
	public void setCourseLevel(int courseLevel) {
		this.courseLevel = courseLevel;
	}
	
	public void setRecipeCode(int recipeCode) {
		this.recipeCode = recipeCode;
	}
	
	public void setRecipeCoursePhoto(String recipeCoursePhoto) {
		this.recipeCoursePhoto = recipeCoursePhoto;
	}
	
	public void setRecipeCourseTime(int recipeCourseTime) {
		this.recipeCourseTime =recipeCourseTime;
	}
	
	public void setRecipeCourseIntro(String recipeCourseIntro) {
		this.recipeCourseIntro = recipeCourseIntro;
	}
	
	public String toString() {
		return "레시피 코드 : "  + recipeCode + " 단계 : "+ courseLevel +"\n조리사진경로 : "  + recipeCoursePhoto + 
			" 조리시간 : " + recipeCourseTime + " 조리소개 : " + recipeCourseIntro;  
	}
}
