//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RecipeIngredientDTO.java
//  @ Date : 2014-05-13
//  @ Author : 
//
//




public class RecipeIngredientDTO 
{
	private int recipeIngredientCode;
	private int ingredientCode;
	private int recipeCode;
	private int recipeIngredientNum;
	
	public RecipeIngredientDTO()
	{
		this(0,0,0,0);
	}
	public RecipeIngredientDTO(int recipeIngredientCode, int ingredientCode, int recipeCode, int recipeIngredientNum) 
	{
		this.recipeIngredientCode = recipeIngredientCode;
		this.ingredientCode = ingredientCode;
		this.recipeCode = recipeCode;
		this.recipeIngredientNum = recipeIngredientNum;
	}
	public int getRecipeIngredientCode() 
	{
		return recipeIngredientCode;
	}
	
	public int getIngredientCode() 
	{
		return ingredientCode;
	}
	public int getRecipeCode() 
	{
		return recipeCode;
	}
	public int getRecipeIngredientNum() 
	{
		return recipeIngredientNum;
	}
	public void setRecipeIngredientCode(int recipeIngredientCode) 
	{
		this.recipeIngredientCode = recipeIngredientCode;
	}
	public void setIngredientCode(int ingredientCode) 
	{
		this.ingredientCode = ingredientCode;
	}
	public void setRecipeCode(int recipeCode) 
	{
		this.recipeCode = recipeCode;
	}
	public void setRecipeIngredientNum(int recipeIngredientNum) 
	{
		this.recipeIngredientNum = recipeIngredientNum;
	}
	public String toString() 
	{
		return ""+ recipeIngredientCode + ingredientCode + recipeCode + recipeIngredientNum;
	}
}
