//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RegisterController.java
//  @ Date : 2014-04-29
//  @ Author : 
//
//


import javax.swing.*;
import java.awt.event.*;

public class RegisterController {
	public FoodInfo foodInfo;
	public RecipeInfo recipeInfo;
	public RegisterController() 
	{
		this(new JTextField(),new JTextField(),new JTextField(),new JTextArea(),new JTextField(),new JTextField(),
			new JComboBox<String>(),new JTextField(), new JTextArea());	
	}
	
	public RegisterController(JTextField foodName, JTextField foodCalorie, JTextField foodPhoto, JTextArea foodIntro, JTextField cookingTotalTime, JTextField portion, JComboBox<String> levelComboBox, JTextField totalIngredient, JTextArea tip)throws NumberFormatException
	{
		String name = foodName.getText();
		String intro = foodIntro.getText();
		String photo = foodPhoto.getText();

		int calorie = Integer.parseInt(foodCalorie.getText());	
		int totalTime = Integer.parseInt(cookingTotalTime.getText());
		String tipText = tip.getText();
		int portionNum = Integer.parseInt(portion.getText());
		TempRecipeIngreInfoList.setFoodName(name);
		TempRecipeIngreInfoList.setFoodCode(Integer.toString(FoodRecipeInfoList.getFoodRecipeInfoList().size()+1));
		//객체를 만든다.
		this.foodInfo = new FoodInfo(name,intro,photo,calorie);

		this.recipeInfo = new RecipeInfo(name,totalTime,tipText,portionNum,Level.valueOf(levelComboBox.getSelectedItem().toString())
			,new CookingCourseList(TempCookingCourseList.getCookingCourseList(),foodName.getText(),"")
			,new RecipeIngreInfoList(foodName.getText(),"1",TempRecipeIngreInfoList.getRecipeIngreInfoList()));
	}
	public void register() {
		FoodRecipeInfo obj = new FoodRecipeInfo(foodInfo,recipeInfo);
		FoodRecipeInfoList.addFoodRecipeInfoList(obj);
		AddRecipeFileController obj2 = new AddRecipeFileController(foodInfo,recipeInfo);
		obj2.writeFoodInfoFile();
		obj2.writeRecipeIngreInfoFile();
		obj2.writeRecipeInfoFile();
		obj2.writeCookingCourseListFile();
		
	}
	
	public FoodInfo getFoodInfo() 
	{
		return this.foodInfo;
	}
	
	public RecipeInfo getRecipeInfo() 
	{
		return this.recipeInfo;
	}
	
	public void setFoodInfo(FoodInfo foodInfo)
	{
		this.foodInfo = foodInfo;
	}
	
	public void setRecipeInfo(RecipeInfo recipeInfo) 
	{
		this.recipeInfo = recipeInfo;	
	}
}
