//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StoreDAO.java
//  @ Date : 2014-05-13
//  @ Author : 
//
//
import java.sql.*;

public class StoreDAO {
	private Connection conn;
	
	public StoreDAO() 
	{
		connect();
	}
	private void connect() 
	{
		DBConnectionPool instance = DBConnectionPool.getInstance();
		try
		{
			conn=instance.getConnection();	
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
	}
	
	public void disconnect()
	{
		try
		{
			if(conn != null)
			{
				conn.close();
				System.out.println("DB와의 접속을 끊었습니다.");
			}
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
	
	}
	
	public int insert(int storeCode, String storeName, String storeAddress, String storePhone) 
	{
		int rowNum = 0;
		Statement stmt = null;
		try
		{
			stmt = conn.createStatement();
			rowNum = stmt.executeUpdate("insert into store_tb values("+storeCode+","+storeName+","+storeAddress+","+storePhone+")");
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch(Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return rowNum;
	}
	
	public StoreList selectAll() 
	{
		StoreDTO info = null;
		Statement stmt = null;
		StoreList list = new StoreList();

		try
		{
			stmt = conn.createStatement();
			ResultSet rs = stmt.executeQuery("select * from store_tb");
			while(rs.next())
			{
				int storeCode = rs.getInt("storeCode");
				String storeName = rs.getString("storeName");
				String storeAddress = rs.getString("storeAddress");
				String storePhone = rs.getString("storePhone");
				
				info = new StoreDTO(storeCode,storeName,storeAddress,storePhone);
				list.addStoreList(info);
			}
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return list;
	
	}
	
	public StoreDTO selectStoreCode(int storeCode) 
	{
		StoreDTO info = null;
		Statement stmt = null;
		

		try
		{
			stmt = conn.createStatement();
			ResultSet rs = stmt.executeQuery("select * from store_tb where storeCode = "+storeCode+"");
			while(rs.next())
			{
				int storeCode1 = rs.getInt("storeCode");
				String storeName = rs.getString("storeName");
				String storeAddress = rs.getString("storeAddress");
				String storePhone = rs.getString("storePhone");
				
				info = new StoreDTO(storeCode1,storeName,storeAddress,storePhone);
				
			}
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return info;
	}
	
	public StoreList selectStoreName(String storeName) 
	{
		StoreDTO info = null;
		Statement stmt = null;
		StoreList list = new StoreList();

		try
		{
			stmt = conn.createStatement();
			ResultSet rs = stmt.executeQuery("select * from store_tb where storeName = '"+storeName+"'");
			while(rs.next())
			{
				int storeCode = rs.getInt("storeCode");
				String storeName1 = rs.getString("storeName");
				String storeAddress = rs.getString("storeAddress");
				String storePhone = rs.getString("storePhone");
				
				info = new StoreDTO(storeCode,storeName1,storeAddress,storePhone);
				list.addStoreList(info);
			}
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return list;
	}
	
	public StoreDTO selectStoreAddress(String storeAddress) 
	{
		StoreDTO info = null;
		Statement stmt = null;
		

		try
		{
			stmt = conn.createStatement();
			ResultSet rs = stmt.executeQuery("select * from store_tb where storeAddress = '"+storeAddress+"'");
			while(rs.next())
			{
				int storeCode = rs.getInt("storeCode");
				String storeName = rs.getString("storeName");
				String storeAddress1 = rs.getString("storeAddress");
				String storePhone = rs.getString("storePhone");
				
				info = new StoreDTO(storeCode,storeName,storeAddress1,storePhone);
				
			}
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return info;
	}
	
	public StoreDTO selectStorePhone(String storePhone) 
	{
		StoreDTO info = null;
		Statement stmt = null;
		
		try
		{
			stmt = conn.createStatement();
			ResultSet rs = stmt.executeQuery("select * from store_tb where storePhone ='"+storePhone+"'");
			while(rs.next())
			{
				int storeCode = rs.getInt("storeCode");
				String storeName = rs.getString("storeName");
				String storeAddress = rs.getString("storeAddress");
				String storePhone1 = rs.getString("storePhone");
				
				info = new StoreDTO(storeCode,storeName,storeAddress,storePhone1);
			
			}
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return info;
	}
	
	public int updateAll(int storeCode, String storeName, String storeAddress, String storePhone) 
	{
		int res = 0;
		Statement stmt = null;
		try
		{
			stmt = conn.createStatement();
			res = stmt.executeUpdate("update store_tb set storeName = '"+storeName+"',storeAddress = '"+storeAddress+"',storePhone = '"+storePhone+"' where storeCode = "+storeCode+"");
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return res;
	}
	
	public int updateStoreName(int storeCode, String storeName) 
	{
		int res = 0;
		Statement stmt = null;
		try
		{
			stmt = conn.createStatement();
			res = stmt.executeUpdate("update store_tb set storeName = '"+storeName+"'where storeCode = "+storeCode+"");
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return res;
	
	}
	
	public int updateStoreAddress(int storeCode, String storeAddress) 
	{
		int res = 0;
		Statement stmt = null;
		try
		{
			stmt = conn.createStatement();
			res = stmt.executeUpdate("update store_tb set storeAddress = '"+storeAddress+"'where storeCode = "+storeCode+"");
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return res;
	
	}
	
	public int updateStorePhone(int storeCode, String storePhone) 
	{
		int res = 0;
		Statement stmt = null;
		try
		{
			stmt = conn.createStatement();
			res = stmt.executeUpdate("update store_tb set storePhone = '"+storePhone+"' where storeCode = "+storeCode+"");
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return res;
	}
	
	public int deleteAll()
	{
		int res = 0;
		Statement stmt = null;
		try
		{
			stmt = conn.createStatement();
			res = stmt.executeUpdate("delete from store_tb ");
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return res;
	}
	public int deleteStoreCode(int storeCode) 
	{
		int res = 0;
		Statement stmt = null;
		try
		{
			stmt = conn.createStatement();
			res = stmt.executeUpdate("delete from store_tb where storeCode = "+storeCode+"");
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return res;
	}
	
	public int deleteStoreName(String storeName) 
	{
		int res = 0;
		Statement stmt = null;
		try
		{
			stmt = conn.createStatement();
			res = stmt.executeUpdate("delete from store_tb where storeName = '"+storeName+"'");
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return res;
	}	
	public int deleteStoreAddress(String storeAddress) 
	{
		int res = 0;
		Statement stmt = null;
		try
		{
			stmt = conn.createStatement();
			res = stmt.executeUpdate("delete from store_tb where '"+storeAddress+"'");
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return res;
	
	}
	public int deleteStroePhone(String storePhone) 
	{
		int res = 0;
		Statement stmt = null;
		try
		{
			stmt = conn.createStatement();
			res = stmt.executeUpdate("delete from store_tb where '"+storePhone+"'");
		}
		catch (SQLException se)
		{
			System.out.println(se.getMessage());
		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
		finally
		{
			try
			{
				if(stmt != null)
					stmt.close();
			}
			catch (SQLException se)
			{
				System.out.println(se.getMessage());
			}
		}
		return res;
	}
	//------------------------------- get/set --------------------
	public Connection getConn() 
	{
		return conn;
	}

	public void setConn(Connection conn) 
	{
		this.conn = conn;
	}
}
