//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StoreDTO.java
//  @ Date : 2014-05-13
//  @ Author : 
//
//




public class StoreDTO 
{
	private int storeCode;
	private String storeName;
	private String storeAddress;
	private String storePhone;

	public StoreDTO() 
	{
		this(0,null,null,null);
	}
	
	public StoreDTO(int storeCode, String storeName, String storeAddress, String storePhone) 
	{
		this.storeCode = storeCode;
		this.storeName = storeName;
		this.storeAddress = storeAddress;
		this.storePhone = storePhone;
	}
	public int getStoreCode() 
	{
		return storeCode;
	}
	public String getStoreName() 
	{
		return storeName;
	}
	public String getStoreAddress() 
	{
		return storeAddress;
	}
	public String getStorePhone() 
	{
		return storePhone;
	}
	public void setStoreCode(int storeCode) 
	{
		this.storeCode = storeCode;
	}
	public void setStoreName(String storeName) 
	{
		this.storeName = storeName;
	}
	public void setStoreAddress(String storeAddress) 
	{
		this.storeAddress = storeAddress;
	}
	
	public void setStorePhone(String storePhone) 
	{
		this.storePhone = storePhone;
	}
	public String toString() 
	{
		return storeCode + storeName + storeAddress + storePhone;
	}
}
