//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : 판매처정보.java
//  @ Date : 2014-04-28
//  @ Author : 양진영
//
//
import java.util.*;
public class StoreInfoList {
	private Collection<StoreInfo> list;
	public StoreInfoList() {
		this(new LinkedList<StoreInfo>());
	}
	
	public StoreInfoList(Collection<StoreInfo> list) {
		this.list=list;
	}
	
	public Collection<StoreInfo> getList() {
		return this.list;
	}
	
	public void setList(Collection<StoreInfo> list) {
		this.list=list;
	}
	
	public StoreInfo addStoreInfoList(StoreInfo storeInfo) {
		if(list.add(storeInfo))
			return storeInfo;
		else
			return null;
	}
	public StoreInfo reviseStoreInfoList(String code, StoreInfo storeInfo) {
		int i=0;
		for(StoreInfo tmp:list)
		{
			if(tmp.getStoreCode().equals(code))
			{
				((LinkedList<StoreInfo>)list).set(i,storeInfo);
				return storeInfo;
			}
			i++;
		}
		return null;
	}
	public StoreInfo removeStoreInfoList(String code) {
		for(StoreInfo tmp:list)
		{
			if(tmp.getStoreCode().equals(code))
			{
				list.remove(tmp);
				return tmp;
			}
		}
		return null;
	}
	public StoreInfo searchStoreInfo(String code) {
		for(StoreInfo tmp:list)
		{
			if(tmp.getStoreCode().equals(code))
				return tmp;
		}
		return null;
	}
}
